#!/usr/bin/env python3
"""
Regenerates every table and headline number reported in the paper directly
from results/*.csv and results/*.json -- the raw output of
notebooks/federated_digital_twins_AUTO_all_datasets.ipynb.

This script exists so that every number in the paper is independently
checkable: run this against results/, compare the printed output to the
tables in paper/main.tex, and see for yourself that they match. Nothing
here is generated, estimated, or rounded differently than what appears in
the paper.

Usage:
    pip install -r ../requirements.txt
    python generate_tables.py

Requires: results/ciciot/, results/edgeiiot/, results/nbaiot/ populated
(already included in this repository) or regenerated by re-running the
notebook against fresh Kaggle downloads.
"""
import json
import os
import sys

import pandas as pd

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
DATASETS = ["ciciot", "edgeiiot", "nbaiot"]
DATASET_LABEL = {"ciciot": "CICIoT2023", "edgeiiot": "Edge-IIoTset", "nbaiot": "N-BaIoT"}


def path(ds, fname):
    return os.path.join(RESULTS_DIR, ds, fname)


def header(title):
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def table_single_attacker():
    header("Table III: Single-attacker results (macro-F1)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table4_single_attacker.csv"))
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print(df.to_string(index=False))


def table_baselines():
    header("Table IV: Baseline comparison, 3-of-N-twin attack (F1 drop, mean of 5 seeds)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table5_baselines.csv"))
        g = df.groupby("method").agg(clean_f1=("clean_f1", "mean"), poison_f1=("poison_f1", "mean"))
        g["drop"] = (g["clean_f1"] - g["poison_f1"]).round(3)
        print(f"\n--- {DATASET_LABEL[ds]} (n={df['seed'].nunique()} seeds) ---")
        print(g[["drop"]].to_string())


def table_ablation():
    header("Table V: Ablation, caught / 15 rounds (mean of 5 seeds)")
    for ds in DATASETS:
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        blunt = pd.read_csv(path(ds, "table6_ablation_blunt.csv"))
        stealth = pd.read_csv(path(ds, "table7_ablation_stealthy.csv"))
        print("Blunt:", blunt.groupby("variant")["caught"].mean().round(1).to_dict())
        print("Stealthy:", stealth.groupby("variant")["caught"].mean().round(1).to_dict())


def table_adaptive():
    header("Table VI: Fixed vs. locally-adaptive attacker (mean +/- std, 5 seeds)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table8_adaptive.csv"))
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print(f"  Fixed:    caught={df.fixed_caught.mean():.1f}+/-{df.fixed_caught.std():.1f}  "
              f"F1={df.fixed_f1.mean():.3f}+/-{df.fixed_f1.std():.3f}")
        print(f"  Adaptive: caught={df.adaptive_caught.mean():.1f}+/-{df.adaptive_caught.std():.1f}  "
              f"F1={df.adaptive_f1.mean():.3f}+/-{df.adaptive_f1.std():.3f}")


def table_sensitivity():
    header("Table VII: Threshold sensitivity, attacked macro-F1 (single seed=100)")
    for ds in DATASETS:
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        k_df = pd.read_csv(path(ds, "table9_sensitivity_k.csv"))
        w_df = pd.read_csv(path(ds, "table9_sensitivity_wmax.csv"))
        print("k:", k_df.groupby("k")["poison_f1"].mean().round(3).to_dict())
        print("Wmax:", w_df.groupby("wcap")["poison_f1"].mean().round(3).to_dict())


def long_horizon():
    header("Section VI-F: Long-horizon behavior")
    for ds in DATASETS:
        d = json.load(open(path(ds, "longhorizon.json")))
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print("eps=0 trace:   ", d["drift_trace_eps0"])
        print("eps=0.05 trace:", d["drift_trace_eps005"])
        print("detection@15:  ", d["detection_at_15_rounds"])


def table_generalization():
    header("Table VIII: Cross-dataset generalization (mean of 5 seeds)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table10_generalization.csv"))
        m = df.mean(numeric_only=True)
        print(f"{DATASET_LABEL[ds]}: catch={100*m['catch_rate']:.1f}%  fp={100*m['fp_rate']:.1f}%  "
              f"gate_recovers={m['gate_recovers']:.3f}")


def fairness():
    header("Section VI-H: Fairness")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "fairness.csv"))
        n_twins = 9 if ds == "nbaiot" else 8
        corr = df[["dominant_frac", "vetoes"]].corr().iloc[0, 1]
        print(f"{DATASET_LABEL[ds]}: {df['vetoes'].sum()} / {len(df)*15} false vetoes, "
              f"correlation with class skew r={corr:.2f}")


def table_headline():
    header("Table IX / Fig. 2: Severity sweep, macro-F1 (mean of 5 seeds) -- THE HEADLINE RESULT")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table_headline_severity_sweep.csv"))
        g = df.groupby("n_poisoned")[["f1_nogate", "f1_gate"]].mean().round(3)
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print(g.to_string())


def table_strong_attacks():
    header("Table X: Parameter-space attacks, caught/15, mean F1 (mean of 5 seeds)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table_strong_attacks.csv"))
        g = df.groupby("attack")[["caught", "f1"]].mean().round(3)
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print(g.to_string())


def table_peer_aware():
    header("Table XI: Peer-aware attacker, caught/15, F1 (mean of 5 seeds)")
    for ds in DATASETS:
        df = pd.read_csv(path(ds, "table_peer_aware_attacker.csv"))
        g = df.groupby("mode")[["caught", "f1"]].mean().round(3)
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print(g.to_string())


def noniid_scalability_zscore():
    header("Section VI-K: non-IID sweep, scalability, Z-score separation")
    for ds in DATASETS:
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        noniid = pd.read_csv(path(ds, "table_noniid_dirichlet.csv"))
        fp = noniid.groupby("alpha")["fp_twin_rounds"].mean().round(1)
        print("Non-IID FP events per seed by alpha:", fp.to_dict())

        scal = pd.read_csv(path(ds, "table_scalability.csv"))
        print("Scalability (N, s/round, F1):",
              list(zip(scal.n_clients, scal.seconds_per_round.round(3), scal.f1.round(3))))

        z = pd.read_csv(path(ds, "zscore_distribution.csv"))
        h, m = z[z.type == "honest"]["z"], z[z.type == "malicious"]["z"]
        print(f"Z-score: honest max={h.max():.2f}, "
              f"honest>=4: {100*(h>=4).mean():.1f}%, malicious>=4: {100*(m>=4).mean():.1f}%")


def convergence_aware():
    header("Fig. 5: Convergence-aware threshold vs. fixed thresholds")
    for ds in DATASETS:
        d = json.load(open(path(ds, "convergence_aware_gate.json")))
        print(f"\n--- {DATASET_LABEL[ds]} ---")
        print("Fixed eps=0:   ", d["trace_fixed_eps0"])
        print("Fixed eps=0.05:", d["trace_fixed_eps005"])
        print("Adaptive:      ", d["trace_adaptive"])


def main():
    if not os.path.isdir(RESULTS_DIR):
        sys.exit(f"results/ not found at {RESULTS_DIR} -- run this from analysis/, "
                 f"or re-run the notebook to regenerate results/ first.")
    table_single_attacker()
    table_baselines()
    table_ablation()
    table_adaptive()
    table_sensitivity()
    long_horizon()
    table_generalization()
    fairness()
    table_headline()
    table_strong_attacks()
    table_peer_aware()
    noniid_scalability_zscore()
    convergence_aware()
    print("\n" + "=" * 70)
    print("Done. Compare every number above against paper/main.tex.")
    print("=" * 70)


if __name__ == "__main__":
    main()
